server:
  port: 9090
spring:
  application:
    name: GATEWAY-SERVICE
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallBack
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallBack
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack
okta:
  oauth2:
    issuer: https://dev-95099325.okta.com/oauth2/default
    audience: api://default
    client-id: 0oae0rl6tqZwQh4T95d7
    client-secret: u0PSx12W8Kf7BMsNmMAiW5IH6DY7anTGkl0LEi7tnqnY9lCHoxNrSY0QljWumY9F
    scopes: openid, email, profile, offline_access