server:
  port: 9090
spring:
  application:
    name: GATEWAY-SERVICE
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/order/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: ORDER-SERVICE
#                fallback:
#                  uri: forward:/orderServiceFallBack
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payment/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: PAYMENT-SERVICE
#                fallback:
#                  uri: forward:/paymentServiceFallBack
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/product/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: PRODUCT-SERVICE
#                fallback:
#                  uri: forward:/productServiceFallBack