groups:
  - name: kafka-performance-alerts
    rules:
      - alert: HighMessageProcessingTime
        expr: kafka_message_processing_time_seconds_sum / kafka_message_processing_time_seconds_count > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High message processing time detected"
          description: "Message processing time is {{ $value }}s"

      - alert: LowMessageThroughput
        expr: rate(kafka_messages_processed_total[5m]) < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low message throughput"
          description: "Message throughput is {{ $value }} messages/sec"

      - alert: HighJVMMemoryUsage
        expr: (jvm_memory_used_bytes{area="heap"} / jvm_memory_max_bytes{area="heap"}) * 100 > 80
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High JVM memory usage"
          description: "JVM heap usage is {{ $value }}%"